version: "3.5"

services:

  backend:
    build: 
      context: ./backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/backend
    networks:
      - local-net

networks:
  local-net:
    driver: bridge