REST_API_ENDPOINT="https://api.crypto.com/v2/"
REST_UAT_SANDBOX_ENDPOINT="https://uat-api.3ona.co/v2/"
WSS_UAT_SANDBOX_ENDPOINT_USER="wss://uat-stream.3ona.co/v2/user"
WSS_UAT_SANDBOX_ENDPOINT_MARKET="wss://uat-stream.3ona.co/v2/market"
WSS_PRODUCTION_USER="wss://stream.crypto.com/v2/user"
WSS_PRODUCTION_MARKET="wss://stream.crypto.com/v2/market"
DD="CIAO"

MINUTE_1="1m"
MINUTE_5="5m"
MINUTE_15="15m"
MINUTE_30="30m"
HOUR_1="1h"
HOUR_4="4h"
HOUR_6="6h"
HOUR_12="12h"
DAY_1="1D"
DAY_7="7D"
DAY_14="14D"
MONTH_1="1M"

BTC_USD = "BTC_USD"