# CRYPTO.COM API
REST_API_ENDPOINT="https://api.crypto.com/v2/"
REST_UAT_SANDBOX_ENDPOINT="https://uat-api.3ona.co/v2/"
WSS_UAT_SANDBOX_ENDPOINT_USER="wss://uat-stream.3ona.co/v2/user"
WSS_UAT_SANDBOX_ENDPOINT_MARKET="wss://uat-stream.3ona.co/v2/market"
WSS_PRODUCTION_USER="wss://stream.crypto.com/v2/user"
#WSS_PRODUCTION_MARKET="wss://stream.crypto.com/v2/market"
WSS_PRODUCTION_MARKET="wss://stream.binance.com:443"
BINANCE_ENDPOINT = "https://api.binance.com/api/v3/"


#DATABASE
DATABASE_MARKET="Market_Trades"
DATABASE_TRACKER="Tracker"
DATABASE_BENCHMARK="Benchmark"
DATABASE_LOGGING="Logging"
DATABASE_TRADING="Trading"

#COLLECTION FOR DATABASE TRADING
COLLECTION_TRADING_LIVE="Live"
COLLECTION_TRADING_STRATEGY1="Strategy1"
#COLLECTION FOR DATABASE LOGGING
DATABASE_API_ERROR="API_Error"
DATABASE_TRACKER_INFO="Tracker_Info"
DATABASE_BENCHMARK_INFO="Benchmark_Info"
DATABASE_TRADING_INFO="Trading_Info"


# TIMEFRAME
MINUTE_1="1m"
MINUTE_5="5m"
MINUTE_15="15m"
MINUTE_30="30m"
HOUR_1="1h"
HOUR_4="4h"
HOUR_6="6h"
HOUR_12="12h"
DAY_1="1D"
DAY_7="7D"
DAY_14="14D"
MONTH_1="1M"

# PARAMETERS FOR FETCHING DATA
NUMBER_COINS_TO_TRADE_WSS = 441
NUMBER_COINS_TO_TRADE=20
SLICES=8
COINS_PRIORITY=10
SLEEP_SECONDS=0.8
SLEEP_SECONDS_BTC_ETH=0.1
LIMIT=1000


#PARAMETER FOR AUTHORIZATION
SECRET_KEY = "3148a55fb6cb73cb67f7e8bb8c5a631d7127b5b5f3fe7db0c1a8139f7793a06a"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60*24*3650
clients_oauth2 = {
    "Crypto_User_2023!": {
        "username": "Crypto_User_2023!",
        "hashed_password": "$2b$12$HdmhpU5RyeOfjuYu/8w81OciGkE/mrGyBenp6iTCt.4MZCG6qSSbS",
        "disabled": False
    },
}
ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJDcnlwdG9fVXNlcl8yMDIzISIsImV4cCI6MTk5NjE0ODAwOH0.kv5FpZBLrCShvwIeccqh01qMeBihA1ySs43MrjM5AEc"