# CRYPTO.COM API
REST_API_ENDPOINT="https://api.crypto.com/v2/"
REST_UAT_SANDBOX_ENDPOINT="https://uat-api.3ona.co/v2/"
WSS_UAT_SANDBOX_ENDPOINT_USER="wss://uat-stream.3ona.co/v2/user"
WSS_UAT_SANDBOX_ENDPOINT_MARKET="wss://uat-stream.3ona.co/v2/market"
WSS_PRODUCTION_USER="wss://stream.crypto.com/v2/user"
WSS_PRODUCTION_MARKET="wss://stream.crypto.com/v2/market"
BINANCE_ENDPOINT = "https://api.binance.com/api/v3/"

#DATABASE
COLLECTION_TRADES_OVER_Q="Trades_over_q"
COLLECTION_ALL_TRADES="All_Trades"
COLLECTION_VOLUME_STATISTICS="VolumeStatistics"
DATABASE_MARKET="Market_Trades"
DATABASE_TRACKER="Tracker"
DATABASE_BENCHMARK="Benchmark"

# TIMEFRAME
MINUTE_1="1m"
MINUTE_5="5m"
MINUTE_15="15m"
MINUTE_30="30m"
HOUR_1="1h"
HOUR_4="4h"
HOUR_6="6h"
HOUR_12="12h"
DAY_1="1D"
DAY_7="7D"
DAY_14="14D"
MONTH_1="1M"

# PARAMETERS FOR FETCHING DATA
NUMBER_COINS_TO_TRADE=25
SLICES=8
COINS_PRIORITY=10
SLEEP_SECONDS=0.8
LIMIT=1000